//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::education::Entity as Education;
pub use super::media::Entity as Media;
pub use super::project::Entity as Project;
pub use super::refresh_token::Entity as RefreshToken;
pub use super::resume::Entity as Resume;
pub use super::user::Entity as User;
pub use super::work::Entity as Work;
